# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Scenario3(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "https://uat.orthofi.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_scenario3(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        # Login as TC
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing.tc@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Patients").click()
        driver.find_element_by_css_selector("a.btn.add").click()
        driver.find_element_by_id("FirstName").clear()
        driver.find_element_by_id("FirstName").send_keys("Patient")
        driver.find_element_by_id("LastName").clear()
        driver.find_element_by_id("LastName").send_keys("Automation")
        driver.find_element_by_id("DateOfBirth").clear()
        driver.find_element_by_id("DateOfBirth").send_keys("01012001")
        driver.find_element_by_id("Guardian_UserProfile_FirstName").clear()
        driver.find_element_by_id("Guardian_UserProfile_FirstName").send_keys("Parent1")
        driver.find_element_by_id("Guardian_UserProfile_LastName").clear()
        driver.find_element_by_id("Guardian_UserProfile_LastName").send_keys("Automation")
        driver.find_element_by_id("Guardian_UserProfile_UserName").clear()
        driver.find_element_by_id("Guardian_UserProfile_UserName").send_keys("parent1.automation@orthofi.com")
        driver.find_element_by_id("Guardian_CellPhone").clear()
        driver.find_element_by_id("Guardian_CellPhone").send_keys("3039999999")
        # Select Exam Type: NPE
        driver.find_element_by_id("Exam_ExamDate").click()
        driver.find_element_by_link_text("1").click()
        driver.find_element_by_id("Exam_ExamTime").click()
        driver.find_element_by_css_selector("fieldset.form-group.patient-exam").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Complete Forms").click()
        driver.find_element_by_css_selector("span.ui-icon.ui-icon-closethick").click()
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_id("ConfirmPassword").clear()
        driver.find_element_by_id("ConfirmPassword").send_keys("Password1!")
        driver.find_element_by_id("SecurityQuestion").clear()
        driver.find_element_by_id("SecurityQuestion").send_keys("Question")
        driver.find_element_by_id("SecurityAnswer").clear()
        driver.find_element_by_id("SecurityAnswer").send_keys("Answer")
        driver.find_element_by_id("TOS").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Click "I Agree" on HIPPA form
        # Contact Info Form
        driver.find_element_by_xpath("(//input[@id='Patient_Sex'])[2]").click()
        driver.find_element_by_id("Patient_Address1").clear()
        driver.find_element_by_id("Patient_Address1").send_keys("99999 Tester Lane")
        driver.find_element_by_id("Patient_PostalCode").clear()
        driver.find_element_by_id("Patient_PostalCode").send_keys("80234")
        driver.find_element_by_id("Patient_City").clear()
        driver.find_element_by_id("Patient_City").send_keys("Denver")
        Select(driver.find_element_by_id("Patient_StateTerritory_Abbreviation")).select_by_visible_text("Colorado")
        driver.find_element_by_id("Guardian_DateOfBirth").clear()
        driver.find_element_by_id("Guardian_DateOfBirth").send_keys("01011971")
        driver.find_element_by_xpath("(//input[@id='Guardian_Sex'])[2]").click()
        driver.find_element_by_id("SameAsPatient").click()
        driver.find_element_by_xpath("(//input[@id='Guardian_MaritalStatus'])[2]").click()
        driver.find_element_by_id("Guardian_RelationshipToPatient").click()
        driver.find_element_by_xpath("(//input[@id='PrimaryContactIsFinanciallyResponsible'])[2]").click()
        driver.find_element_by_id("TreatmentReason").clear()
        driver.find_element_by_id("TreatmentReason").send_keys("Jacked Teeth")
        driver.find_element_by_id("DentistIsNotListed").click()
        driver.find_element_by_id("ReferringDentistOther").clear()
        driver.find_element_by_id("ReferringDentistOther").send_keys("Dr No")
        # Select Treatment Sliders!!!
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Medical History Form
        Select(driver.find_element_by_id("LastAppointmentId")).select_by_visible_text("Between 6 months and 12 months")
        driver.find_element_by_id("CurrentPhysicalHealth").click()
        driver.find_element_by_id("IsOnBirthControl").click()
        driver.find_element_by_xpath("(//input[@id='IsPregnant'])[2]").click()
        driver.find_element_by_id("CurrentlyUnderPhysicianCare").click()
        # Select Medical Conditions
        driver.find_element_by_id("ConfirmedMedicalHistory").click()
        driver.find_element_by_name("Submit").click()
        driver.find_element_by_xpath("//form[@id='frmCreate']/fieldset/div[3]/div/div/div/ul/li").click()
        Select(driver.find_element_by_id("InsuranceInfo_0__CarrierId")).select_by_visible_text("Metlife")
        driver.find_element_by_xpath("//fieldset[@id='sizcache08612576538315275']/div[4]/div/ul/li[2]/span").click()
        driver.find_element_by_xpath("//fieldset[@id='sizcache08612576538315275']/div[4]/div[6]/ul/li[2]/span").click()
        driver.find_element_by_id("InsuranceInfo_0__SubscriberMemberNumber").clear()
        driver.find_element_by_id("InsuranceInfo_0__SubscriberMemberNumber").send_keys("456789")
        driver.find_element_by_xpath("//div[@id='pnlAdditionalCoverage']/ul/li[2]").click()
        driver.find_element_by_id("sizcache08612576538315275").click()
        driver.find_element_by_id("GavePermission").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Flexible Financing Form
        driver.find_element_by_xpath("//form[@id='frmFlexibleFinancing']/div[4]/div/div/div[2]/span").click()
        driver.find_element_by_id("ShareAccount").click()
        driver.find_element_by_id("FinancialContact_UserProfile_FirstName").clear()
        driver.find_element_by_id("FinancialContact_UserProfile_FirstName").send_keys("Parent2")
        driver.find_element_by_id("FinancialContact_UserProfile_LastName").clear()
        driver.find_element_by_id("FinancialContact_UserProfile_LastName").send_keys("Automation")
        driver.find_element_by_id("sizcache08901614881211066").click()
        driver.find_element_by_id("FinancialContact_DateOfBirth").clear()
        driver.find_element_by_id("FinancialContact_DateOfBirth").send_keys("02/02/1972")
        driver.find_element_by_id("FinancialContact_Sex").click()
        driver.find_element_by_id("AddressSameAsPatient").click()
        driver.find_element_by_id("FinancialContact_CellPhone").clear()
        driver.find_element_by_id("FinancialContact_CellPhone").send_keys("(303)999-9999")
        driver.find_element_by_xpath("(//input[@id='FinancialContact_DoesOwn'])[2]").click()
        Select(driver.find_element_by_id("FinancialContact_TimeAtAddressId")).select_by_visible_text("Between 12 months and 18 months")
        Select(driver.find_element_by_id("FinancialContact_TimeAtPreviousAddressId")).select_by_visible_text("Between 12 months and 18 months")
        Select(driver.find_element_by_id("FinancialContact_EmploymentStatusId")).select_by_visible_text("Employed")
        Select(driver.find_element_by_id("FinancialContact_TimeAtEmployerId")).select_by_visible_text("Between 6 months and 12 months")
        driver.find_element_by_id("FinancialContact_Employer").clear()
        driver.find_element_by_id("FinancialContact_Employer").send_keys("Automation")
        driver.find_element_by_id("FinancialContact_Occupation").clear()
        driver.find_element_by_id("FinancialContact_Occupation").send_keys("Tester")
        Select(driver.find_element_by_id("FinancialContact_TimeAtPreviousEmployerId")).select_by_visible_text("Between 12 months and 18 months")
        driver.find_element_by_id("FinancialContact_PreviousEmployer").clear()
        driver.find_element_by_id("FinancialContact_PreviousEmployer").send_keys("Testing")
        driver.find_element_by_id("FinancialContact_PreviousOccupation").clear()
        driver.find_element_by_id("FinancialContact_PreviousOccupation").send_keys("Automating")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Login as TC
        driver.find_element_by_link_text("close").click()
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing.tc@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Dashboard").click()
        driver.find_element_by_name("ExamFilterType").click()
        # CheatSheet
        driver.find_element_by_link_text("CS").click()
        self.assertEqual("Between 6 months and 12 months", driver.find_element_by_xpath("//form[@id='frmCheatSheet']/div[7]/fieldset/fieldset/div[2]/div").text)
        self.assertEqual("Dr No", driver.find_element_by_xpath("//form[@id='frmCheatSheet']/div[7]/fieldset/fieldset/div/div").text)
        Select(driver.find_element_by_id("PatientExamResultId")).select_by_visible_text("Observation")
        driver.find_element_by_id("sizcache027689191223698884").click()
        driver.find_element_by_xpath("(//input[@id='IsExamScheduled'])[2]").click()
        driver.find_element_by_id("ObservationFutureExamTypeId").click()
        driver.find_element_by_id("ObservationFutureExamDate").click()
        driver.find_element_by_link_text("7").click()
        driver.find_element_by_xpath("//form[@id='frmCheatSheet']/div[13]/button").click()
        driver.find_element_by_id("txtPin").clear()
        driver.find_element_by_id("txtPin").send_keys("Password1!")
        driver.find_element_by_link_text("Dashboard").click()
        driver.find_element_by_xpath("(//input[@name='ExamFilterType'])[2]").click()
        # Verify Information
        driver.find_element_by_link_text("Verify Info").click()
        driver.find_element_by_xpath("//form[@id='frmVerifyInfo']/div[3]/fieldset/div[3]/div/div/span").click()
        driver.find_element_by_xpath("//form[@id='frmVerifyInfo']/div[4]/fieldset/div[3]/div/div/span").click()
        driver.find_element_by_xpath("//form[@id='frmVerifyInfo']/div[5]/fieldset/div[3]/div/div[2]/span").click()
        driver.find_element_by_xpath("//form[@id='frmVerifyInfo']/div[6]/fieldset/div[3]/div/div/span").click()
        driver.find_element_by_id("PrimaryContactPassword").clear()
        driver.find_element_by_id("PrimaryContactPassword").send_keys("Password1!")
        driver.find_element_by_id("btnAuthenticate").click()
        driver.find_element_by_id("btnRealSubmit").click()
        # Insurance Information Form
        driver.find_element_by_xpath("//form[@id='frmCreate']/fieldset/div[3]/div/div/div/ul/li").click()
        Select(driver.find_element_by_id("InsuranceInfo_0__CarrierId")).select_by_visible_text("Cigna Dental")
        driver.find_element_by_xpath("//fieldset[@id='sizcache014152000069703508']/div[4]/div/ul/li[2]/span").click()
        driver.find_element_by_xpath("//fieldset[@id='sizcache014152000069703508']/div[4]/div[6]/ul/li[2]/span").click()
        driver.find_element_by_id("InsuranceInfo_0__SubscriberMemberNumber").clear()
        driver.find_element_by_id("InsuranceInfo_0__SubscriberMemberNumber").send_keys("987654")
        driver.find_element_by_xpath("//div[@id='pnlAdditionalCoverage']/ul/li[2]").click()
        driver.find_element_by_id("GavePermission").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Finish").click()
        driver.find_element_by_link_text("Log Out").click()
        # Login as Admin
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.btn-default").click()
        driver.find_element_by_link_text("Insurance").click()
        driver.find_element_by_id("Tomorrow").click()
        driver.find_element_by_id("Today").click()
        driver.find_element_by_link_text("U").click()
        # Select the "New" insurance Carrier
        driver.find_element_by_link_text("Edit Eligibility").click()
        driver.find_element_by_id("createNewCarrier").click()
        driver.find_element_by_id("carriername").clear()
        driver.find_element_by_id("carriername").send_keys("Auto-Test Cigna Dental")
        driver.find_element_by_id("carrierphone").clear()
        driver.find_element_by_id("carrierphone").send_keys("(877)555-5555")
        driver.find_element_by_id("next").click()
        driver.find_element_by_link_text("Subscriber Info").click()
        self.assertEqual("987654", driver.find_element_by_id("SubscriberId").get_attribute("value"))
        driver.find_element_by_link_text("Patient Info").click()
        driver.find_element_by_id("PatientGroupName").clear()
        driver.find_element_by_id("PatientGroupName").send_keys("Auto-Test")
        driver.find_element_by_id("PatientGroupNumber").clear()
        driver.find_element_by_id("PatientGroupNumber").send_keys("009009")
        driver.find_element_by_id("LifetimeMax").clear()
        driver.find_element_by_id("LifetimeMax").send_keys("1000")
        driver.find_element_by_id("LifetimeUsed").clear()
        driver.find_element_by_id("LifetimeUsed").send_keys("0")
        driver.find_element_by_id("MaxCoverage").clear()
        driver.find_element_by_id("MaxCoverage").send_keys("50")
        driver.find_element_by_id("MinAge").clear()
        driver.find_element_by_id("MinAge").send_keys("1")
        driver.find_element_by_id("MaxAge").clear()
        driver.find_element_by_id("MaxAge").send_keys("99")
        driver.find_element_by_id("MaxAgeStudent").clear()
        driver.find_element_by_id("MaxAgeStudent").send_keys("26")
        driver.find_element_by_xpath("(//input[@id='IsPreAuthRequired'])[2]").click()
        driver.find_element_by_id("CoordinationOfBenefitsId").click()
        driver.find_element_by_id("IsAllowsAssignmentOfBenefits").click()
        driver.find_element_by_id("PolicyEffectiveDate").clear()
        driver.find_element_by_id("PolicyEffectiveDate").send_keys("01/01/2015")
        driver.find_element_by_id("PlanBenefitsStart").clear()
        driver.find_element_by_id("PlanBenefitsStart").send_keys("01/01/2015")
        driver.find_element_by_id("PlanBenefitsEnd").clear()
        driver.find_element_by_id("PlanBenefitsEnd").send_keys("12/31/2015")
        driver.find_element_by_id("verifyPatient").click()
        driver.find_element_by_id("select2-chosen-1").click()
        driver.find_element_by_link_text("Save Check & Set Priority").click()
        self.assertEqual("Insurance Eligibility Check Complete", driver.find_element_by_xpath("//div[@id='OrthoFiInsuranceSummaryApp']/div[5]/div/div/div/div[3]/div/div/div/div/div/div/div/table/tbody/tr[2]/td[4]").text)
        driver.find_element_by_link_text("Automation Testing").click()
        driver.find_element_by_link_text("Log Off").click()
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing.tc@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Dashboard").click()
        driver.find_element_by_link_text("Action").click()
        # Select Tx Recommended
        driver.find_element_by_id("TreatmentType").click()
        driver.find_element_by_name("Dentition").click()
        driver.find_element_by_name("Severity").click()
        driver.find_element_by_id("cb_674").click()
        driver.find_element_by_id("tll_674").clear()
        driver.find_element_by_id("tll_674").send_keys("12")
        driver.find_element_by_id("tlh_674").clear()
        driver.find_element_by_id("tlh_674").send_keys("18")
        driver.find_element_by_id("btnAdd").click()
        driver.find_element_by_xpath("(//input[@id='TreatmentType'])[2]").click()
        driver.find_element_by_name("Dentition").click()
        driver.find_element_by_name("Severity").click()
        driver.find_element_by_id("cb_674").click()
        driver.find_element_by_id("tll_674").clear()
        driver.find_element_by_id("tll_674").send_keys("12")
        driver.find_element_by_id("tlh_674").clear()
        driver.find_element_by_id("tlh_674").send_keys("18")
        # Select Additional Cost
        driver.find_element_by_id("txAddCost_662").click()
        # Select {New Courtesy}
        driver.find_element_by_xpath("(//input[@value=''])[16]").clear()
        driver.find_element_by_xpath("(//input[@value=''])[16]").send_keys("Referral")
        driver.find_element_by_xpath("(//input[@value=''])[17]").clear()
        driver.find_element_by_xpath("(//input[@value=''])[17]").send_keys("500.00")
        self.assertEqual("on", driver.find_element_by_id("txCourtesy_-1").get_attribute("value"))
        driver.find_element_by_id("btnSubmit").click()
        # Medical Credit Check Authorization
        driver.find_element_by_id("SSN").clear()
        driver.find_element_by_id("SSN").send_keys("999-99-9999")
        driver.find_element_by_xpath("(//button[@name='action'])[2]").click()
        # Payment Slider
        driver.find_element_by_id("monthlyPaymentAmount").click()
        driver.find_element_by_id("mainSliderWrapper").click()
        driver.find_element_by_id("btnFinish").click()
        driver.find_element_by_id("btnSignLater").click()
        driver.find_element_by_link_text("31").click()
        driver.find_element_by_link_text("Set Date").click()
        driver.find_element_by_xpath("//table[@id='exams']/tbody/tr[2]/td[8]/div/a/span").click()
        driver.find_element_by_link_text("Choose Plan").click()
        # Payment Slider
        driver.find_element_by_id("btnFinish").click()
        driver.find_element_by_id("select2-chosen-1").click()
        driver.find_element_by_id("btnChangeDueDay").click()
        driver.find_element_by_id("DocumentTerms_1__Term_TermInitials").clear()
        driver.find_element_by_id("DocumentTerms_1__Term_TermInitials").send_keys("PA")
        driver.find_element_by_id("DocumentTerms_2__Term_TermInitials").clear()
        driver.find_element_by_id("DocumentTerms_2__Term_TermInitials").send_keys("PA")
        driver.find_element_by_id("DocumentTerms_3__Term_TermInitials").clear()
        driver.find_element_by_id("DocumentTerms_3__Term_TermInitials").send_keys("PA")
        driver.find_element_by_id("DocumentTerms_4__Term_TermInitials").clear()
        driver.find_element_by_id("DocumentTerms_4__Term_TermInitials").send_keys("PA")
        driver.find_element_by_id("DocumentTerms_5__Term_TermInitials").clear()
        driver.find_element_by_id("DocumentTerms_5__Term_TermInitials").send_keys("PA")
        driver.find_element_by_id("DocumentTerms_7__Term_TermInitials").clear()
        driver.find_element_by_id("DocumentTerms_7__Term_TermInitials").send_keys("PA")
        driver.find_element_by_xpath("//div[@id='wrap']/div/div/div[2]/div/form/button").click()
        driver.find_element_by_id("Signature").clear()
        driver.find_element_by_id("Signature").send_keys("Witness 4 Automation")
        # ERROR: Caught exception [Error: Dom locators are not implemented yet!]
        driver.find_element_by_id("select2-chosen-2").click()
        driver.find_element_by_id("StaffPin").clear()
        driver.find_element_by_id("StaffPin").send_keys("Password1!")
        driver.find_element_by_xpath("//div[@id='wrap']/div/div/div[2]/div/form/button").click()
        driver.find_element_by_id("select2-chosen-1").click()
        driver.find_element_by_id("TenderTypeReferenceNumber").clear()
        driver.find_element_by_id("TenderTypeReferenceNumber").send_keys("90909")
        driver.find_element_by_css_selector("button.btn.submit").click()
        self.assertEqual("Your Payment was Successful", driver.find_element_by_css_selector("div.display-group > div").text)
        # ERROR: Caught exception [unknown command []]
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
