# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re

class Scenario4(unittest.TestCase):
    def setUp(self):
        self.driver = webdriver.Firefox()
        self.driver.implicitly_wait(30)
        self.base_url = "https://uat.orthofi.com/"
        self.verificationErrors = []
        self.accept_next_alert = True
    
    def test_scenario4(self):
        driver = self.driver
        driver.get(self.base_url + "/")
        # Login as TC
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing.tc@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Patients").click()
        driver.find_element_by_css_selector("a.btn.add").click()
        driver.find_element_by_id("FirstName").clear()
        driver.find_element_by_id("FirstName").send_keys("Patient")
        driver.find_element_by_id("LastName").clear()
        driver.find_element_by_id("LastName").send_keys("Automation")
        driver.find_element_by_id("DateOfBirth").clear()
        driver.find_element_by_id("DateOfBirth").send_keys("12231994")
        driver.find_element_by_id("PatientIsPrimaryContact").click()
        driver.find_element_by_id("Guardian_UserProfile_UserName").clear()
        driver.find_element_by_id("Guardian_UserProfile_UserName").send_keys("patient.automation@orthofi.com")
        driver.find_element_by_id("Guardian_CellPhone").clear()
        driver.find_element_by_id("Guardian_CellPhone").send_keys("3039999999")
        # Select Exam Type: NPE
        driver.find_element_by_id("Exam_ExamDate").clear()
        driver.find_element_by_id("Exam_ExamDate").send_keys("12/10/2014")
        driver.find_element_by_id("Exam_RecordsDate").click()
        driver.find_element_by_link_text("6").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Dashboard").click()
        driver.find_element_by_xpath("(//input[@name='ExamFilterType'])[4]").click()
        driver.find_element_by_link_text("Action").click()
        driver.find_element_by_link_text("Pre-Populate Forms").click()
        driver.find_element_by_id("Patient_Sex").click()
        driver.find_element_by_id("Patient_Address1").clear()
        driver.find_element_by_id("Patient_Address1").send_keys("99999 Tester Lane")
        driver.find_element_by_id("Patient_PostalCode").clear()
        driver.find_element_by_id("Patient_PostalCode").send_keys("80234")
        driver.find_element_by_id("Patient_City").clear()
        driver.find_element_by_id("Patient_City").send_keys("Denver")
        Select(driver.find_element_by_id("Patient_StateTerritory_Abbreviation")).select_by_visible_text("Colorado")
        driver.find_element_by_id("AddressSameAsPatient").click()
        driver.find_element_by_id("PrimaryContact_MaritalStatus").click()
        driver.find_element_by_xpath("(//input[@id='PrimaryContact_RelationshipToPatient'])[8]").click()
        driver.find_element_by_id("btnAddInsurance").click()
        Select(driver.find_element_by_id("InsuranceInfo_0__CarrierId")).select_by_visible_text("Aetna Dental")
        driver.find_element_by_id("InsuranceInfo_0__PopulateFromPrimaryContact").click()
        driver.find_element_by_id("InsuranceInfo_0__SubscriberMemberNumber").clear()
        driver.find_element_by_id("InsuranceInfo_0__SubscriberMemberNumber").send_keys("123456")
        driver.find_element_by_id("InsuranceInfo_0__SubscriberSSN").clear()
        driver.find_element_by_id("InsuranceInfo_0__SubscriberSSN").send_keys("999-99-9999")
        driver.find_element_by_id("InsuranceInfo_0__PopulateFromPatient2").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Automation Tester").click()
        driver.find_element_by_link_text("Log Off").click()
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Login as Admin
        driver.find_element_by_link_text("Insurance").click()
        driver.find_element_by_id("select2-result-label-153").click()
        driver.find_element_by_link_text("U").click()
        driver.find_element_by_link_text("Search by Group").click()
        driver.find_element_by_id("CarrierSearchGroupName").clear()
        driver.find_element_by_id("CarrierSearchGroupName").send_keys("TBD")
        driver.find_element_by_xpath("(//a[contains(text(),'Use')])[2]").click()
        driver.find_element_by_id("next").click()
        # E-Check Page
        driver.find_element_by_id("runECheck").click()
        self.assertEqual("Fail", driver.find_element_by_css_selector("span.text-error").text)
        self.assertEqual("123456", driver.find_element_by_id("EcheckSubscriberId").get_attribute("value"))
        driver.find_element_by_id("EcheckSubscriberId").clear()
        driver.find_element_by_id("EcheckSubscriberId").send_keys("654321")
        driver.find_element_by_id("useECheckInfo").click()
        driver.find_element_by_link_text("Subscriber Info").click()
        self.assertEqual("654321", driver.find_element_by_id("SubscriberId").get_attribute("value"))
        driver.find_element_by_id("next").click()
        # Patient Info
        driver.find_element_by_id("PatientGroupName").clear()
        driver.find_element_by_id("PatientGroupName").send_keys("Auto-Test")
        driver.find_element_by_id("PatientGroupNumber").clear()
        driver.find_element_by_id("PatientGroupNumber").send_keys("009009")
        driver.find_element_by_id("LifetimeMax").clear()
        driver.find_element_by_id("LifetimeMax").send_keys("1000")
        driver.find_element_by_id("LifetimeUsed").clear()
        driver.find_element_by_id("LifetimeUsed").send_keys("0")
        driver.find_element_by_id("MaxCoverage").clear()
        driver.find_element_by_id("MaxCoverage").send_keys("50")
        driver.find_element_by_id("MinAge").clear()
        driver.find_element_by_id("MinAge").send_keys("1")
        driver.find_element_by_id("MaxAge").clear()
        driver.find_element_by_id("MaxAge").send_keys("99")
        driver.find_element_by_id("MaxAgeStudent").clear()
        driver.find_element_by_id("MaxAgeStudent").send_keys("26")
        driver.find_element_by_xpath("(//input[@id='IsPreAuthRequired'])[2]").click()
        driver.find_element_by_id("CoordinationOfBenefitsId").click()
        driver.find_element_by_xpath("(//input[@id='IsAllowsAssignmentOfBenefits'])[2]").click()
        driver.find_element_by_id("PolicyEffectiveDate").clear()
        driver.find_element_by_id("PolicyEffectiveDate").send_keys("01/01/2015")
        driver.find_element_by_id("PlanBenefitsStart").clear()
        driver.find_element_by_id("PlanBenefitsStart").send_keys("01/01/2015")
        driver.find_element_by_id("PlanBenefitsEnd").clear()
        driver.find_element_by_id("PlanBenefitsEnd").send_keys("12/31/2015")
        driver.find_element_by_id("verifyPatient").click()
        driver.find_element_by_id("select2-chosen-1").click()
        driver.find_element_by_link_text("Save Check & Set Priority").click()
        self.assertEqual("Insurance Eligibility Check Complete", driver.find_element_by_xpath("//div[@id='OrthoFiInsuranceSummaryApp']/div[5]/div/div/div/div[3]/div/div/div/div/div/div/div/table/tbody/tr[2]/td[4]").text)
        driver.find_element_by_link_text("Automation Testing").click()
        driver.find_element_by_link_text("Log Off").click()
        # Login as TC
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing.tc@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Dashboard").click()
        driver.find_element_by_link_text("Action").click()
        driver.find_element_by_link_text("Reschedule").click()
        driver.find_element_by_id("em-NewDate").click()
        driver.find_element_by_link_text("7").click()
        driver.find_element_by_css_selector("div.exammanagement-form-actions > a.btn.submit").click()
        driver.find_element_by_xpath("(//input[@name='ExamFilterType'])[2]").click()
        driver.find_element_by_link_text("Action").click()
        driver.find_element_by_link_text("Complete Forms").click()
        driver.find_element_by_css_selector("span.ui-icon.ui-icon-closethick").click()
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_id("ConfirmPassword").clear()
        driver.find_element_by_id("ConfirmPassword").send_keys("Password1!")
        driver.find_element_by_id("SecurityQuestion").clear()
        driver.find_element_by_id("SecurityQuestion").send_keys("Question")
        driver.find_element_by_id("SecurityAnswer").clear()
        driver.find_element_by_id("SecurityAnswer").send_keys("Answer")
        driver.find_element_by_id("TOS").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_id("Guardian_Sex").click()
        driver.find_element_by_id("Patient_EmergencyContactName").clear()
        driver.find_element_by_id("Patient_EmergencyContactName").send_keys("Parent1 Automation")
        driver.find_element_by_id("Patient_EmergencyContactPhone").clear()
        driver.find_element_by_id("Patient_EmergencyContactPhone").send_keys("(303)999-1111")
        driver.find_element_by_id("Patient_EmergencyContactRelationshipToPatient").clear()
        driver.find_element_by_id("Patient_EmergencyContactRelationshipToPatient").send_keys("Mother")
        driver.find_element_by_id("PrimaryContactIsFinanciallyResponsible").click()
        driver.find_element_by_id("TreatmentReason").clear()
        driver.find_element_by_id("TreatmentReason").send_keys("Jacked teeth")
        driver.find_element_by_id("sizcache06893640630470703").click()
        driver.find_element_by_id("DentistIsNotListed").click()
        driver.find_element_by_id("ReferringDentistOther").clear()
        driver.find_element_by_id("ReferringDentistOther").send_keys("Dr No")
        # Select Treatment Sliders!!!
        driver.find_element_by_css_selector("button.btn.submit").click()
        Select(driver.find_element_by_id("LastAppointmentId")).select_by_visible_text("Between 18 months and 24 months")
        driver.find_element_by_xpath("(//input[@id='CurrentPhysicalHealth'])[2]").click()
        driver.find_element_by_id("CurrentlyUnderPhysicianCare").click()
        # Select Medical Conditions
        driver.find_element_by_id("ConfirmedMedicalHistory").click()
        driver.find_element_by_name("Submit").click()
        # Insurance Form
        driver.find_element_by_id("InsuranceInfo_0__SubscriberGender").click()
        driver.find_element_by_xpath("(//input[@id='InsuranceInfo_0__RelationshipToPatient'])[8]").click()
        driver.find_element_by_xpath("//div[@id='pnlAdditionalCoverage']/ul/li[2]").click()
        driver.find_element_by_id("GavePermission").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Flexible Financing
        driver.find_element_by_id("FinancialContact_DoesOwn").click()
        Select(driver.find_element_by_id("FinancialContact_TimeAtAddressId")).select_by_visible_text("Longer than 24 months")
        Select(driver.find_element_by_id("FinancialContact_EmploymentStatusId")).select_by_visible_text("Unemployed")
        driver.find_element_by_id("SsnHolder").clear()
        driver.find_element_by_id("SsnHolder").send_keys("999999999")
        driver.find_element_by_id("btnRealSubmit").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_css_selector("span.ui-icon.ui-icon-closethick").click()
        # Login as TC
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing.tc@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Dashboard").click()
        driver.find_element_by_id("txtPin").clear()
        driver.find_element_by_id("txtPin").send_keys("Password1!")
        driver.find_element_by_link_text("Action").click()
        # Select Tx Recommended
        driver.find_element_by_id("TreatmentType").click()
        driver.find_element_by_name("Dentition").click()
        driver.find_element_by_name("Severity").click()
        driver.find_element_by_id("cb_674").click()
        driver.find_element_by_id("tll_674").clear()
        driver.find_element_by_id("tll_674").send_keys("12")
        driver.find_element_by_id("tlh_674").clear()
        driver.find_element_by_id("tlh_674").send_keys("18")
        driver.find_element_by_id("btnAdd").click()
        driver.find_element_by_xpath("(//input[@id='TreatmentType'])[2]").click()
        driver.find_element_by_name("Dentition").click()
        driver.find_element_by_name("Severity").click()
        driver.find_element_by_id("cb_674").click()
        driver.find_element_by_id("tll_674").clear()
        driver.find_element_by_id("tll_674").send_keys("12")
        driver.find_element_by_id("tlh_674").clear()
        driver.find_element_by_id("tlh_674").send_keys("18")
        # Select Additional Cost
        driver.find_element_by_id("txAddCost_662").click()
        # Select Second Additional Cost
        driver.find_element_by_id("txAddCost_661").click()
        # Select {New Courtesy}
        driver.find_element_by_xpath("(//input[@value=''])[16]").clear()
        driver.find_element_by_xpath("(//input[@value=''])[16]").send_keys("Referral")
        driver.find_element_by_xpath("(//input[@value=''])[17]").clear()
        driver.find_element_by_xpath("(//input[@value=''])[17]").send_keys("500.00")
        self.assertEqual("on", driver.find_element_by_id("txCourtesy_-1").get_attribute("value"))
        # Select {New Courtesy}
        driver.find_element_by_xpath("(//input[@value=''])[18]").clear()
        driver.find_element_by_xpath("(//input[@value=''])[18]").send_keys("Firefighter")
        driver.find_element_by_xpath("(//input[@value=''])[19]").clear()
        driver.find_element_by_xpath("(//input[@value=''])[19]").send_keys("500.00")
        self.assertEqual("on", driver.find_element_by_id("txCourtesy_-1").get_attribute("value"))
        driver.find_element_by_id("btnSubmit").click()
        # Payment Slider
        driver.find_element_by_id("txtPin").clear()
        driver.find_element_by_id("txtPin").send_keys("Password1!")
        driver.find_element_by_id("btnPrint").click()
        driver.find_element_by_id("btnHome").click()
        driver.find_element_by_id("FollowUpDate").click()
        driver.find_element_by_link_text("7").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Login as TC
        driver.find_element_by_id("txtPin").clear()
        driver.find_element_by_id("txtPin").send_keys("Password1!")
        driver.find_element_by_id("btnEnterPin").click()
        driver.find_element_by_xpath("(//input[@name='ExamFilterType'])[5]").click()
        driver.find_element_by_link_text("Automation, Patient").click()
        driver.find_element_by_link_text("Communications").click()
        driver.find_element_by_link_text("+ New Communication").click()
        driver.find_element_by_id("CommunicationMethodId").click()
        driver.find_element_by_id("DateOfCommuncation").click()
        driver.find_element_by_link_text("6").click()
        driver.find_element_by_id("Notes").clear()
        driver.find_element_by_id("Notes").send_keys("Notes for Test Communication.\n\nAutomation Testing")
        # Select "Set Follow-Up Date" from Outcome
        driver.find_element_by_id("OutcomeDate").click()
        driver.find_element_by_link_text("6").click()
        # Select Reason
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Dashboard
        driver.find_element_by_link_text("Dashboard").click()
        driver.find_element_by_id("sizcache07371661410613863").click()
        driver.find_element_by_xpath("(//input[@name='ExamFilterType'])[3]").click()
        driver.find_element_by_link_text("change pc").click()
        driver.find_element_by_xpath("(//input[@id='PrimaryGuardianId'])[2]").click()
        driver.find_element_by_id("NewGuardianUserName").clear()
        driver.find_element_by_id("NewGuardianUserName").send_keys("parent.automation@orthofi.com")
        driver.find_element_by_id("NewGuardianFirstName").clear()
        driver.find_element_by_id("NewGuardianFirstName").send_keys("Parent1")
        driver.find_element_by_id("NewGuardianLastName").clear()
        driver.find_element_by_id("NewGuardianLastName").send_keys("Automation")
        driver.find_element_by_id("btnManageSave").click()
        driver.find_element_by_css_selector("span.ui-icon.ui-icon-closethick").click()
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_id("ConfirmPassword").clear()
        driver.find_element_by_id("ConfirmPassword").send_keys("Password1!")
        driver.find_element_by_id("Phone").clear()
        driver.find_element_by_id("Phone").send_keys("(303)999-9999")
        driver.find_element_by_id("SecurityQuestion").clear()
        driver.find_element_by_id("SecurityQuestion").send_keys("Question")
        driver.find_element_by_id("SecurityAnswer").clear()
        driver.find_element_by_id("SecurityAnswer").send_keys("Answer")
        driver.find_element_by_id("TOS").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        # Agree to HIPPA
        driver.find_element_by_id("Guardian_DateOfBirth").clear()
        driver.find_element_by_id("Guardian_DateOfBirth").send_keys("01/01/1971")
        driver.find_element_by_id("Guardian_Sex").click()
        driver.find_element_by_id("SameAsPatient").click()
        driver.find_element_by_xpath("(//input[@id='Guardian_MaritalStatus'])[2]").click()
        driver.find_element_by_xpath("(//input[@id='Guardian_RelationshipToPatient'])[2]").click()
        driver.find_element_by_id("PrimaryContactIsFinanciallyResponsible").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_name("Submit").click()
        driver.find_element_by_id("sizcache009613706794353793").click()
        driver.find_element_by_id("GavePermission").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        Select(driver.find_element_by_id("FinancialContact_TimeAtAddressId")).select_by_visible_text("Longer than 24 months")
        Select(driver.find_element_by_id("FinancialContact_EmploymentStatusId")).select_by_visible_text("Retired")
        driver.find_element_by_id("btnRealSubmit").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_css_selector("span.ui-icon.ui-icon-closethick").click()
        driver.find_element_by_id("UserName").clear()
        driver.find_element_by_id("UserName").send_keys("automation.testing.tc@orthofi.com")
        driver.find_element_by_id("Password").clear()
        driver.find_element_by_id("Password").send_keys("Password1!")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_link_text("Action").click()
        driver.find_element_by_link_text("Adjust Tx Details").click()
        driver.find_element_by_id("select2-chosen-1").click()
        driver.find_element_by_id("btnSubmit").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_id("btnSubmit").click()
        self.assertRegexpMatches(driver.find_element_by_id("lblInsurance").text, r"^exact:\$0\.00[\s\S]*$")
        # Test Hover Over Message
        # Adjust Slider to Pay in Full
        driver.find_element_by_id("btnFinish").click()
        driver.find_element_by_id("Signature").clear()
        driver.find_element_by_id("Signature").send_keys("Parent1 Automation")
        driver.find_element_by_id("SignerIsRP").click()
        driver.find_element_by_id("WitnessSignature").clear()
        driver.find_element_by_id("WitnessSignature").send_keys("Automation Testing")
        driver.find_element_by_id("StaffPin").clear()
        driver.find_element_by_id("StaffPin").send_keys("Password1!")
        driver.find_element_by_xpath("//div[@id='wrap']/div/div/div[2]/div/form/button").click()
        # Select Credit Card Payment Type
        driver.find_element_by_id("CreditCardNumber").clear()
        driver.find_element_by_id("CreditCardNumber").send_keys("4111111111111111")
        driver.find_element_by_id("CCV").clear()
        driver.find_element_by_id("CCV").send_keys("123")
        driver.find_element_by_css_selector("button.btn.submit").click()
        driver.find_element_by_id("select2-chosen-4").click()
        driver.find_element_by_css_selector("button.btn.submit").click()
        self.assertEqual("Your Payment was Successful", driver.find_element_by_css_selector("div.display-group > div").text)
        # ERROR: Caught exception [unknown command []]
    
    def is_element_present(self, how, what):
        try: self.driver.find_element(by=how, value=what)
        except NoSuchElementException, e: return False
        return True
    
    def is_alert_present(self):
        try: self.driver.switch_to_alert()
        except NoAlertPresentException, e: return False
        return True
    
    def close_alert_and_get_its_text(self):
        try:
            alert = self.driver.switch_to_alert()
            alert_text = alert.text
            if self.accept_next_alert:
                alert.accept()
            else:
                alert.dismiss()
            return alert_text
        finally: self.accept_next_alert = True
    
    def tearDown(self):
        self.driver.quit()
        self.assertEqual([], self.verificationErrors)

if __name__ == "__main__":
    unittest.main()
